### ISSUE TITLE
QCA988x Mesh mode support

### ISSUE THREAD

**Issue by DanielRIOT** [greearb/ath10k-ct#174] opened 2020-12-08 13:54 UTC
Trying to get Mesh mode on a Compex WLE900VX ( QCA9880 hw2.0 )
IW reports that the mode and frame types are supported, but mesh isn't listed for the interface, might be related to #68 and #75 or might not...

( I'm trying to run AP and Mesh simultaneously )

* OpenWrt SNAPSHOT, r14966-7330348f2d ( Master on IPQ806x )
* ath10k-firmware-qca988x-ct-full-htt
* ath10k-ct

```
 cat /sys/kernel/debug/ieee80211/phy2/ath10k/firmware_info
directory: ath10k/QCA988X/hw2.0
firmware:  ct-firmware-2.bin
fwcfg:     fwcfg-pci-0002:01:00.0.txt
bus:       0002:01:00.0
features:  wmi-10.x,mfp,txstatus-noack,wmi-10.x-CT,ratemask-CT,regdump-CT,txrate-CT,flush-all-CT,pingpong-CT,ch-regs-CT,nop-CT,set-special-CT,get-temp-CT,tx-rc-CT,cust-stats-CT,retry-gt2-CT,txrate2-CT,beacon-cb-CT,wmi-block-ack-CT
version:   10.1-ct-8x-__fH-022-538f0906
hw_rev:    988x
board:     board.bin
```
iw shows that it *should* support mesh, but it isn't listed as a valid interface combination
```
iw phy2 info: 
...
 Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * P2P-device
...
 Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * IBSS: 0x40 0xb0 0xc0 0xd0
                 * managed: 0x40 0xb0 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * mesh point: 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
...		 
 valid interface combinations:
                 * #{ managed, P2P-client } <= 16, #{ P2P-GO } <= 3, #{ AP } <= 16, #{ IBSS } <= 1,
                   total <= 16, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz }
```
on the other card ( WLE1216V2 - QCA9884 ) iw output is the same for the supported TX and RX frames and interface modes, but the _valid interface combinations_ section shows  "Mesh"  ( not P2P ,.. interesting but irrelevant at the moment )- 

This might be an invalid comparison as they are running different firmwares and are different chipsets, just iw Phy outputs are smiliar to a large extent , 10.4-ct( QCA9884 ) vs 10.1-ct ( CQA9880)
```
valid interface combinations for WLE1216V2 ( QCA9884 ):
...
                 * #{ managed } <= 16, #{ AP, mesh point } <= 16, #{ IBSS } <= 1,
                   total <= 16, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 80+80 MHz, 160 MHz }
...
```

**Comment by mpratt14** [comment] 2020-12-18 21:14
actually this is related to / duplicate of #81 

to use true 802.11s you must use the "official" firmware (non-CT) package for chips that use the 10.1 version

`ath10k-firmware-qca988x` and `kmod-ath10k`

**Closed** 2021-08-31 10:23 UTC
